name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    env:
      working-directory: ./js
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          working-directory: ${{env.working-directory}}
      - uses: actions/setup-node@v1 
        with: 
          node-version: '14'
          working-directory: ${{env.working-directory}}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npx nx-cloud start-ci-run
        working-directory: ${{env.working-directory}}
      - run: npx nx affected --target=build --parallel --max-parallel=3
        working-directory: ${{env.working-directory}}
      - run: npx nx affected --target=test --parallel --max-parallel=2
        working-directory: ${{env.working-directory}}
      - run: npx nx-cloud stop-all-agents
        working-directory: ${{env.working-directory}}
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      working-directory: ./js
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          working-directory: ${{env.working-directory}}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          working-directory: ${{env.working-directory}}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npx nx-cloud start-ci-run
        working-directory: ${{env.working-directory}}
      - run: npx nx affected --target=build --parallel --max-parallel=3
        working-directory: ${{env.working-directory}}
      - run: npx nx affected --target=test --parallel --max-parallel=2
        working-directory: ${{env.working-directory}}
      - run: npx nx-cloud stop-all-agents
        working-directory: ${{env.working-directory}}
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14'
          working-directory: ${{env.working-directory}}
      - run: npm install
        working-directory: ${{env.working-directory}}
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
        working-directory: ${{env.working-directory}}
