name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - pre
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  VITE_NEK_FIREBASE_CONFIG: ${{ secrets.NEK_FIREBASE_CONFIG }}
  NX_NEK_FIREBASE_ADMIN_SDK: ${{ secrets.NEK_FIREBASE_ADMIN_SDK }}
  VITE_NEK_RECAPTCHA_V3_SITE_KEY: ${{ secrets.NEK_RECAPTCHA_V3_SITE_KEY }}
  VITE_NEK_FIREBASE_APPCHECK_DEGUG_TOKEN: ${{ secrets.NEK_FIREBASE_APPCHECK_DEBUG_TOKEN }}
jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf # pin@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # pin@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec nx-cloud start-ci-run
      - name: Workspace lint
        run: pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
      - name: Format check
        run: pnpm exec nx-cloud record -- pnpm exec nx format:check
      - name: Lint
        run: pnpm exec nx affected --target=lint --parallel=3
      - name: Test
        run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build
        run: pnpm exec nx affected --target=build --parallel=3
      - run: pnpm exec nx-cloud stop-all-agents
  pre:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf # pin@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # pin@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm exec nx-cloud start-ci-run
      - name: Workspace lint
        run: pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
      - name: Format check
        run: pnpm exec nx-cloud record -- pnpm exec nx format:check
      - name: Lint
        run: pnpm exec nx affected --target=lint --parallel=3
      - name: Test
        run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build
        run: pnpm exec nx affected --target=build --parallel=3
      - run: pnpm exec nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # pin@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: pnpm exec nx-cloud start-agent
