name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - pre
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_NEK_FIREBASE_CONFIG: ${{ secrets.NEK_FIREBASE_CONFIG }}
  NX_NEK_FIREBASE_ADMIN_SDK: ${{ secrets.NEK_FIREBASE_ADMIN_SDK }}
  NX_NEK_RECAPTCHA_V3_SITE_KEY: ${{ secrets.NEK_RECAPTCHA_V3_SITE_KEY }}
  NX_NEK_FIREBASE_APPCHECK_DEBUG_TOKEN: ${{ secrets.NEK_FIREBASE_APPCHECK_DEBUG_TOKEN }}
  NX_PORTFOLIO_FIREBASE_CONFIG: ${{ secrets.PORTFOLIO_FIREBASE_CONFIG }}
  NX_PORTFOLIO_RECAPTCHA_V3_SITE_KEY: ${{ secrets.PORTFOLIO_RECAPTCHA_V3_SITE_KEY }}
  NX_PORTFOLIO_FIREBASE_APPCHECK_DEBUG_TOKEN: ${{ secrets.PORTFOLIO_FIREBASE_APPCHECK_DEBUG_TOKEN }}
jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx-cloud start-ci-run
      - name: Workspace lint
        run: pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
      - name: Format check
        run: pnpm exec nx-cloud record -- pnpm exec nx format:check
      - name: Lint
        run: pnpm exec nx affected --target=lint --parallel=3
      - name: Test
        run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build
        run: pnpm exec nx affected --target=build --parallel=3
      - run: pnpm exec nx-cloud stop-all-agents
  pre:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx-cloud start-ci-run
      - name: Workspace lint
        run: pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
      - name: Format check
        run: pnpm exec nx-cloud record -- pnpm exec nx format:check
      - name: Lint
        run: pnpm exec nx affected --target=lint --parallel=3
      - name: Test
        run: pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
      - name: Build
        run: pnpm exec nx affected --target=build --parallel=3
      - run: pnpm exec nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: pnpm exec nx-cloud start-agent
